//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominiumAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPropiedades
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int PropiedadID { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> ProvinciaID { get; set; }
        public string UbicacionExacta { get; set; }
        public Nullable<int> Habitaciones { get; set; }
        public Nullable<int> Banos { get; set; }
        public string Area { get; set; }
        public Nullable<int> Piso { get; set; }
        public string Estacionamiento { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> IDVendedor { get; set; }
    
        public virtual TUsers TUsers { get; set; }
        public virtual TProvincias TProvincias { get; set; }
    }
}
