//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominiumAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int Id { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public string NombreVisitante { get; set; }
        public string PropiedadVisitada { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public string EstadoVisita { get; set; }
    
        public virtual TUsers TUsers { get; set; }
    }
}
